Add audio
blackfoot-makers/flame-game pull request #20
Opened 2022-07-31 07:34 UTC by tun43p

2022-08-01 07:31 UTC, thingthing requested changes

2022-08-01 07:31 UTC, thingthing commented on lib/main_game/melvyn_plus_plus_game.dart
> +    await _initializeAudio(debug: true);
Autant en faire une variable d'env, comme ça on peut le changer dans la CI

2022-08-01 20:55 UTC, tun43p commented on lib/main_game/melvyn_plus_plus_game.dart
> +    playerRunningAudioPlayer =
J'ai un peu refacto l'AudioController, je sais pas ce que t'en penses 🤷

2022-08-01 21:28 UTC, Nirsu commented on lib/audio/audio_controller.dart
> +  static Future<void> changeLogLevel({bool debug = false}) async {
Normalement si on utilise le linter de blackfoot on as pas le droit de faire de l'assignement :
https://dart-lang.github.io/linter/lints/parameter_assignments.html

2022-08-01 21:35 UTC, thingthing commented on lib/audio/audio_controller.dart
> +  static Future<void> changeLogLevel({bool debug = false}) async {
On a pas le droit de faire de reassignment mais avoir des valeurs par défaut sur les paramètres c'est bon

2022-08-02 07:43 UTC, tun43p commented on lib/audio/audio_controller.dart
> +  static Future<void> changeLogLevel({bool debug = false}) async {
Mais... on pas pas de reassignment la, c'est juste une valeure par défaut sur mon boolean

2022-08-02 10:09 UTC, thingthing requested changes

2022-08-02 10:09 UTC, thingthing commented on lib/audio/audio_controller.dart
> +        maxPlayers: 1,
faudrait l'avoir en paramètre, ou alors mettre 5 en dur (pour les 4 joueurs + le monstre

2022-08-02 19:57 UTC, thingthing requested changes

2022-08-02 19:57 UTC, thingthing commented on lib/audio/audio_controller.dart
> +class AudioInstance {
hm du coup si on s'en sert que dans la classe AudioController (et qu'on l'utilise avec), vaut mieux le mettre en privée comme ça on risque pas de l'utiliser à l'extérieur!

2022-08-03 07:57 UTC, tun43p commented on lib/audio/audio_controller.dart
> +class AudioInstance {
Si je la passe en private, le linter m'envoie ça comme warning https://dart-lang.github.io/linter/lints/library_private_types_in_public_api.html

2022-08-03 09:02 UTC, thingthing commented on lib/audio/audio_controller.dart
> +class AudioInstance {
Ok ignore la règle ici alors parce que ça a du sens de le mettre en privée là

2022-08-03 15:21 UTC, thingthing approved these changes

2022-08-03 16:13 UTC, Nirsu approved these changes

2022-08-03 16:14 UTC, merged