Feat/create collision
blackfoot-makers/flame-game pull request #36
Opened 2022-08-28 18:36 UTC by Nirsu

2022-08-29 10:45 UTC, tun43p approved these changes, later dismissed

2022-08-29 11:34 UTC, thingthing requested changes

2022-08-29 11:34 UTC, thingthing commented on lib/main_game/player.dart
> +    // TODO(ALL): replace by a real sprite + add angle support
t'entends quoi par angle support?

2022-08-29 11:34 UTC, thingthing commented on lib/main_game/player.dart
> +    debugPrint('ON COLLISION');
on peut l'enlever lui non?

2022-08-29 11:34 UTC, thingthing commented on lib/main_game/player.dart
> +    debugPrint('Begin contact');
Lui aussi?

2022-08-29 15:41 UTC, Nirsu commented on lib/main_game/player.dart
> +    // TODO(ALL): replace by a real sprite + add angle support
Aaah le fait de tourner le sprite en fonction de la direction

2022-08-29 15:50 UTC, thingthing approved these changes, later dismissed

2022-09-05 16:02 UTC, tun43p approved these changes

2022-09-05 16:04 UTC, thingthing approved these changes

2022-09-05 16:04 UTC, merged