[FEAT]: add camera border
blackfoot-makers/flame-game pull request #39
Opened 2022-08-29 10:18 UTC by Nirsu

2022-08-29 10:45 UTC, tun43p approved these changes

2022-08-29 13:04 UTC, thingthing requested changes

2022-08-29 13:04 UTC, thingthing commented on lib/main_game/melvyn_plus_plus_game.dart
> +      camera.worldBounds = Rect.fromPoints(
T'as le bloquage du user sur les bords? Sinon mets juste des murs sur le bord de la carte comme ça on est bon

2022-08-29 15:37 UTC, Nirsu commented on lib/main_game/melvyn_plus_plus_game.dart
> +      camera.worldBounds = Rect.fromPoints(
Non pas encore, c'est sur l'autre PR les colisions mais je pense qu'on mettra un mur sur tt le bords yep

2022-08-30 10:53 UTC, thingthing approved these changes

2022-08-30 10:53 UTC, merged