Feature/add soldier class
blackfoot-makers/flame-game pull request #9
Opened 2022-07-30 17:50 UTC by jozacmar

addding multipe basic class and some constructor

2022-07-30 18:16 UTC, thingthing requested changes

2022-07-30 18:16 UTC, thingthing commented on lib/models/model.dart
> +  String path;
devrait être spritePath au moins

2022-07-30 18:16 UTC, thingthing commented on lib/models/model.dart
> +    this.passiv,
passive je crois

2022-07-30 18:16 UTC, thingthing commented on pubspec.yaml
> +  build_runner: ^2.2.0
doit être en dev dependencies

2022-08-01 06:23 UTC, thingthing approved these changes

2022-08-02 14:39 UTC, tun43p approved these changes

2022-08-02 19:53 UTC, merged